### ISSUE TITLE
* and -- issue  infront  of  Address

### ISSUE THREAD

**Issue by drupretys** [MicroHealthLLC/mCMS#232] opened 2017-11-17 18:37 UTC
![image](https://user-images.githubusercontent.com/33326155/32962926-469c957c-cb9c-11e7-8178-b844bb100696.png)
Do  we need * and --

**Comment by LAlexMHllc** [comment] 2017-12-01 17:22
Duplicate of #228

**Closed as completed** 2017-12-07 17:16 UTC
